# Generated by Django 4.2.23 on 2025-02-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0001_initial"),
        ("nautobot_app_vpn", "0002_auto_20250804_0411"),
    ]

    operations = [
        migrations.AddField(
            model_name="ikecrypto",
            name="tenant_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional tenant group association for this profile.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ike_crypto_profiles",
                to="tenancy.tenantgroup",
            ),
        ),
        migrations.AddField(
            model_name="ikecrypto",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional tenant association for this profile.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ike_crypto_profiles",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="ipseccrypto",
            name="tenant_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional tenant group association for this profile.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ipsec_crypto_profiles",
                to="tenancy.tenantgroup",
            ),
        ),
        migrations.AddField(
            model_name="ipseccrypto",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional tenant association for this profile.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ipsec_crypto_profiles",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="ikegateway",
            name="tenant_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional tenant group association for this gateway.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ike_gateways",
                to="tenancy.tenantgroup",
            ),
        ),
        migrations.AddField(
            model_name="ikegateway",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional tenant association for this gateway.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ike_gateways",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="ipsectunnel",
            name="tenant_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional tenant group association for this tunnel.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ipsec_tunnels",
                to="tenancy.tenantgroup",
            ),
        ),
        migrations.AddField(
            model_name="ipsectunnel",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional tenant association for this tunnel.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ipsec_tunnels",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="tunnelmonitorprofile",
            name="tenant_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional tenant group association for this profile.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tunnel_monitor_profiles",
                to="tenancy.tenantgroup",
            ),
        ),
        migrations.AddField(
            model_name="tunnelmonitorprofile",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional tenant association for this profile.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tunnel_monitor_profiles",
                to="tenancy.tenant",
            ),
        ),
    ]
