# .ruff.toml
line-length = 120
target-version = "py311"

[lint]
select = ["E", "F", "W", "B", "I", "S"]
ignore = [
  "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107",
  "D200", "D203", "D205", "D212", "D213", "D400", "D401", "D403", "D415",
  "B904", "S311",  "E501",  # Line too long
  "S105",  # Hardcoded password (we know this is dev only)
  "B006",  # Mutable default
  "E402",  # Import not at top
  "E501","W291",
]
