# nautobot_app_vpn/urls.py
import logging
from django.urls import path
from nautobot.apps.urls import NautobotUIViewSetRouter

# --- Import Specific Views ---
from nautobot_app_vpn.ui.dashboard import VPNDashboardViewSet
from nautobot_app_vpn.ui.ikecrypto import IKECryptoUIViewSet
from nautobot_app_vpn.ui.ikegateway import IKEGatewayUIViewSet
from nautobot_app_vpn.ui.ipseccrypto import IPSecCryptoUIViewSet
from nautobot_app_vpn.ui.ipsectunnel import IPSECTunnelUIViewSet
from nautobot_app_vpn.ui.tunnelmonitor import TunnelMonitorProfileUIViewSet
# Removed PushVPNConfigViewSet import as it wasn't used in the original urls.py


logger = logging.getLogger(__name__)
app_name = "nautobot_app_vpn"

# --- Router for Standard Model Views ---
router = NautobotUIViewSetRouter()
# Keep registrations for standard models
router.register("ikecrypto", IKECryptoUIViewSet, basename="ikecrypto")
router.register("ikegateway", IKEGatewayUIViewSet, basename="ikegateway")
router.register("ipseccrypto", IPSecCryptoUIViewSet, basename="ipseccrypto")
router.register("ipsectunnel", IPSECTunnelUIViewSet, basename="ipsectunnel")
router.register("tunnel-monitor-profiles", TunnelMonitorProfileUIViewSet, basename="tunnelmonitorprofile")
router.register("dashboard", VPNDashboardViewSet, basename="vpn_dashboard")

# --- Explicit Paths for Dashboard and Export ---
urlpatterns = [
    # # Path for the main dashboard view (maps to the 'retrieve' method)
    # path(
    #     "dashboard/",
    #     VPNDashboardViewSet.as_view({"get": "retrieve"}), # Use retrieve for single dashboard page
    #     name="vpn_dashboard", # Keep a simple name
    # ),
    # # Path for the topology export view
    # path(
    #     "dashboard/export/",
    #     VPNTopologyExportView.as_view(),
    #     name="vpn_dashboard_export",
    # ),
    # Include all the URLs generated by the router for the other models
    *router.urls,
]


# logger.info("✅ VPN Plugin URLs registered (Simplified)") # Original log message
logger.info("✅ VPN Plugin URLs registered (Dashboard & Export paths added)")  # Updated log message
