# Generated by Django 4.2.23 on 2025-08-01 07:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_app_vpn", "0003_populate_algorithms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ikegateway",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ikegateway",
            name="last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ikegateway",
            name="liveness_check_interval",
            field=models.PositiveIntegerField(
                blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="ikegateway",
            name="local_id_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="ikegateway",
            name="local_id_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ikegateway",
            name="local_ip",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ikegateway",
            name="peer_device_manual",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ikegateway",
            name="peer_id_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="ikegateway",
            name="peer_id_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ikegateway",
            name="peer_ip",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ikegateway",
            name="peer_location_manual",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ikegateway",
            name="pre_shared_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ipsectunnel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ipsectunnel",
            name="last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ipsectunnel",
            name="monitor_destination_ip",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ipsectunnel",
            name="monitor_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ipsec_tunnels",
                to="nautobot_app_vpn.tunnelmonitorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="ipsectunnel",
            name="role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
